MACOSX_DEPLOYMENT_TARGET:  # [osx and x86_64]
  - '10.14'                # [osx and x86_64]
MACOSX_SDK_VERSION:        # [osx]
  - '10.14'                # [osx and x86_64]
  - '11.3'                 # [osx and arm64]
CONDA_BUILD_SYSROOT:       # [osx]
  - /opt/MacOSX10.14.sdk   # [osx and x86_64]
  - /Library/Developer/CommandLineTools/SDKs/MacOSX11.3.sdk  # [osx and arm64]
c_compiler:  # [win]
  - vs2019   # [win]
cxx_compiler:  # [win]
  - vs2019   # [win]
webengine_version:
  - '5.15.9'
